config/routes.rb
ChessApp::Application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'static_pages#index'
  resources :pieces, only: [:show, :update] do
    member do
      get 'valid_moves'
      put 'promote'
    end
  end
  resources :users, only: [:show, :update] do
    get '/username', to: 'users#username'
  end
  resources :games, only: [:index, :new, :create, :show] do
    put 'forfeit', on: :member
    put 'join', on: :member
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/views/static_pages/index.html.slim
/ Each view is contained with the outer layout and should begin with a row
.row
  .col-xs-12.col-md-8.col-md-offset-2
    h1.text-primary.text-center.title Online Chess

  .col-xs-12.col-md-8.col-md-offset-2.
    h4.body-text
      ' Online Chess is a full-stack, Ruby on Rails web application that allows
      ' for multiple players to play chess (with all rules enforced) and to
      ' receive real-time updates as the opposing player moves and other
      ' relevant game events occur (e.g. a player is put into check).

  .col-xs-12.col-md-8.col-md-offset-2.
    h4.body-text
      ' The application uses best-of-breed methodologies and approaches,
      ' including the use of Agile workflows (i.e. weekly standups, frequent
      ' pairing and code review, etc.). Code that is finally approved for
      ' merging into our master branch is first pushed through a Codeship
      ' Continuous Integration server, which runs a complete suite of tests
      ' as well as a code linter. Code is then pushed into production on a
      ' Heroku server.

  .col-xs-12.col-md-8.col-md-offset-2.
    h4.body-text
      ' Online Chess was built by:
    ul
      li
        h4.body-text
          | Jon Mast (
          a> href="#" Github
          ' |
          a> href="#" LinkedIn
          ' |
          a href="#" Twitter
          |)
      li
        h4.body-text
          | Matthew Dunn (
          a> href="https://github.com/radiofreemattd" Github
          ' |
          a> href="https://www.linkedin.com/in/mshieldsdunn" LinkedIn
          ' |
          a href="https://twitter.com/radiofreemattd" Twitter
          |)
      li
        h4.body-text
          | Saroar (
          a> href="#" Github
          ' |
          a> href="#" LinkedIn
          ' |
          a href="#" Twitter
          |)
      li
        h4.body-text
          | Daniel Rotenberg (
          a> href="#" Github
          ' |
          a> href="#" LinkedIn
          ' |
          a href="#" Twitter
          |)
      li
        h4.body-text
          | Seth Allen (
          a> href="#" Github
          ' |
          a> href="#" LinkedIn
          ' |
          a href="#" Twitter
          |)

  .col-xs-12.col-md-8.col-md-offset-2.
    h4.body-text
      'The Online Chess team was run by Mike Coutermarsh of Product Hunt in San Francisco, CA.

  .col-xs-12.col-md-8.col-md-offset-2.text-center
    =link_to games_path, class: 'btn btn-lg btn-primary'
      | Show me all games
    br
    br
    =link_to 'https://github.com/KnightsOfTheRemoteTable/chess_app', class: 'btn btn-lg btn-primary'
      | Show me the code instead