config/routes.rb
ChessApp::Application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'static_pages#index'
  resources :pieces, only: [:show, :update] do
    member do
      get 'valid_moves'
      put 'promote'
    end
  end
  resources :users, only: [:show, :update] do
    get '/username', to: 'users#username'
  end
  resources :games, only: [:index, :new, :create, :show] do
    put 'forfeit', on: :member
    put 'join', on: :member
  end
end

app/models/game.rb
class Game < ActiveRecord::Base
  HOME_RANK = %w(
    Rook
    Knight
    Bishop
    King
    Queen
    Bishop
    Knight
    Rook
  )

  belongs_to :white_player, class_name: 'User'
  belongs_to :black_player, class_name: 'User'
  belongs_to :winner, class_name: 'User'

  has_many :chess_pieces

  validates :name, presence: true

  enum current_player: [:current_player_is_black_player,
                        :current_player_is_white_player]

  scope :active, -> { where(winner: nil) }

  after_create :populate_board!

  def forfeit_by!(player)
    if player == white_player
      winner = black_player
    else
      winner = white_player
    end
    update!(winner: winner)
  end

  def full?
    players.count == 2
  end

  def players
    [white_player, black_player].compact
  end

  def includes_player?(player)
    players.include?(player)
  end

  def populate_board!
    create_home_rank
    create_pawns
    current_player_is_white_player!
  end

  def state_of_stalemate?(color)
    chess_pieces.with_color(color).each do |piece|
      potential_moves = piece.load_potential_moves
      potential_moves.each { |move| return false if piece.valid_move?(move) && !(piece.move_puts_king_in_check?(move)) }
    end
    true
  end

  def check?
    king_is_in_check?('black') || king_is_in_check?('white')
  end

  def king_is_in_check?(color)
    king = locate_king(color)
    capturable_by_opposing_color?(king)
  end

  def update_current_player!(color)
    color == 'white' ? current_player_is_black_player! : current_player_is_white_player!
  end

  def can_en_passant?(coordinates)
    coordinates == en_passant_coordinates
  end

  def checkmate?
    black_king.checkmate? || white_king.checkmate?
  end

  private

  def en_passant_coordinates
    return unless en_passant_position
    Coordinates.new(*en_passant_position.split(',').map(&:to_i))
  end

  def black_king
    locate_king(:black)
  end

  def white_king
    locate_king(:white)
  end

  def locate_king(color)
    chess_pieces.with_color(color).find_by(type: 'King')
  end

  def capturable_by_opposing_color?(king)
    chess_pieces.with_color(king.opposite_color).find_each do |opponent|
      return true if opponent.valid_move?(king.coordinates)
    end
    false
  end

  def create_home_rank
    HOME_RANK.each_with_index do |type, index|
      chess_pieces.create(type: type, position_x: index + 1, position_y: 1, color: :white)
      chess_pieces.create(type: type, position_x: index + 1, position_y: 8, color: :black)
    end
  end

  def create_pawns
    1.upto(8) do |x|
      chess_pieces.create(type: 'Pawn', position_x: x, position_y: 2, color: :white)
      chess_pieces.create(type: 'Pawn', position_x: x, position_y: 7, color: :black)
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authorize_player, only: :forfeit

  def index
    @games = Game.active.order(created_at: :desc)
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.create(game_params.merge(black_player: current_user))
    if @game.valid?
      flash[:notice] = 'Game created. You are the black player.'
      redirect_to games_path
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def show
    @game = current_game
    @chess_pieces = current_game.chess_pieces.order(:position_y).order(:position_x).to_a
    flash[:alert] = 'The game is in a state of check' if current_game.check?
  end

  def join
    if current_game.white_player.nil? && current_user != current_game.black_player
      current_game.update(white_player: current_user)
      redirect_to current_game, notice: 'You are the white player.'
    else
      render text: 'This game is full or you are trying to play against yourself', status: :unauthorized
    end
  end

  def forfeit
    current_game.forfeit_by!(current_user)
    redirect_to games_path, alert: 'You have forfeited the game'
  end

  private

  def game_params
    params.require(:game).permit(:name)
  end

  def authorize_player
    render text: 'Forbidden', status: :unauthorized unless current_game.players.include?(current_user)
  end

  def current_game
    @game ||= Game.find(params[:id])
  end
end

app/helpers/games_helper.rb
module GamesHelper
  def draw_square(x_axis, y_axis)
    content_tag :div,
                class: "chessboard__row__space chessboard__row__space--#{background_color(x_axis, y_axis)}",
                data: { x: x_axis, y: y_axis } do
      draw_piece(x_axis, y_axis)
    end
  end

  def draw_piece(x_axis, y_axis)
    current_piece = piece_for_square(x_axis, y_axis)

    return unless current_piece

    link_to image_tag("#{current_piece.color.downcase}_#{current_piece.type.downcase}.png"),
            piece_path(current_piece), data: { id: current_piece.id }
  end

  def current_user_can_forfeit?(game)
    return false unless game.winner.nil?
    return false unless game.full?
    game.includes_player?(current_user)
  end
end

app/views/games/create.html.slim
/ Each view is contained with the outer layout and should begin with a row
.row
  .col-xs-12.col-md-8.col-md-offset-2
    h1.text-primary Create
  .col-xs-12.col-md-8.col-md-offset-2
    a href="https://github.com/KnightsOfTheRemoteTable/chess_app" Github

app/views/games/index.html.slim
/ Each view is contained with the outer layout and should begin with a row
.row
  .col-xs-12.col-md-8.col-md-offset-2
    h1.text-primary.title.text-center Current Games

  .col-xs-12.col-md-8.col-md-offset-2
    table.table.table-striped
      tr
        th
          h4.table-heading
            | Game Name
        th
          h4.table-heading
            | Created On
        th
          h4.table-heading
            | Current Players
        th
          h4.table-heading
            | Availability
      - @games.each do |game|
        tr.game
          td
            =link_to game_path(game.id)
              = game.name
          td
            = game.created_at.strftime('%m-%d-%Y')
          td
            a data-toggle="modal" data-target="#myModal" data-playerid="#{game.black_player.id}" =game.black_player.username
            br
            br
            - if !game.white_player.nil?
              a data-toggle="modal" data-target="#myModal" data-playerid="#{game.white_player.id}" =game.white_player.username
            - else
              | ---
          td
            - if game.white_player.nil? && current_user != game.black_player
              = link_to "Join #{game.black_player.username}", join_game_path(game), method: 'PUT'
            - else
              | ---
  .col-xs-12.col-md-8.col-md-offset-2.text-center
    =link_to new_game_path, class: 'btn btn-lg btn-primary'
      | Create a new game

    /Modal
    .modal.fade id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"
      .modal-dialog
        .modal-content
          .modal-header
            button.close type="button" data-dismiss="modal" aria-hidden="true" x
            h4.modal-title id="myModalLabel" Player Overview
          .modal-body
            |
          .modal-footer
            button.btn.btn-primary type="button" data-dismiss="modal" Close

app/views/games/new.html.slim
/ Each view is contained with the outer layout and should begin with a row
.row
  .col-xs-12.col-md-8.col-md-offset-2
    h1.text-primary Create a New Game
  .col-xs-12.col-md-8.col-md-offset-2
    = simple_form_for @game do |f|
      = f.input 'name'
      = f.submit 'Create a new game', class: 'btn btn-lg btn-primary'

app/views/games/show.html.slim
/ Each view is contained with the outer layout and should begin with a row
.row
  .col-xs-12.col-md-8.col-md-offset-2
    .text-center.status
      - if @game.black_player && @game.current_player_is_black_player?
        = "It is black's turn. Black is being played by #{@game.black_player.username}."
      - elsif @game.white_player && @game.current_player_is_white_player?
        = "It is white's turn. White is being played by #{@game.white_player.username}."
      -elsif @game.white_player.nil?
        = "Waiting for another player. It will be white's turn when another player joins."

.row
  .col-xs-12.col-md-8.col-md-offset-2

    /Begin chessboard view
    .chessboard data-channelid="channel-#{@game.id}"
      / A chessboard consists of eight (8) rows, starting (from the top)
      / with a lite-colored row. We can create eight (8) rows by creating
      / four (4) sets of lite-dark alternating rows
      - 1.upto(8) do |y_axis|
        / Create a row starting with the lite color, which we can do by
        / creating four (4) pairs of alternating squares, starting with lite
        .chessboard__row
          - 1.upto(8) do |x_axis|
            = draw_square(x_axis, y_axis)

.row.buttons
  .col-xs-12.text-center
    = link_to 'Forfeit Game', forfeit_game_path(@game), class: 'btn btn-danger btn-lg', method: 'PUT' if current_user_can_forfeit?(@game)